version: '2'
services:
    selfdriving:
        build: .
        container_name: drivelearning
        network_mode: host
        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"
            - "ROS_MASTER_URI=${ROS_MASTER_URI}"
            - "ROS_IP=${ROS_IP}"
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
            - "~/.androvision/dataset:/dataset:rw"
        command: python scripts/learning.py

