DATASET_FILE = "/dataset/dataset.csv"
FRONT_RANGE_TOPIC = "car_sensor/front_range"
SIMPLE_ACTION_TOPIC = "car_command/cmd_simple"
VELOCITY_ACTION_TOPIC = "car_command/cmd_vel"
ANGULAR_KEY = "/angular.z"
LINEAR_KEY = "/linear.x"